# Autogenerated wrapper script for ModularForms_jll for aarch64-apple-darwin
export libmodularforms_jll

using Arb_jll
using FLINT_jll
JLLWrappers.@generate_wrapper_header("ModularForms")
JLLWrappers.@declare_library_product(libmodularforms_jll, "@rpath/libmodularforms_jll-0.1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Arb_jll, FLINT_jll)
    JLLWrappers.@init_library_product(
        libmodularforms_jll,
        "lib/libmodularforms_jll.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
