# Autogenerated wrapper script for ModularForms_jll for i686-linux-musl
export libmodularforms_jll

using Arb_jll
using FLINT_jll
JLLWrappers.@generate_wrapper_header("ModularForms")
JLLWrappers.@declare_library_product(libmodularforms_jll, "libmodularforms_jll.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Arb_jll, FLINT_jll)
    JLLWrappers.@init_library_product(
        libmodularforms_jll,
        "lib/libmodularforms_jll.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
